### PR TITLE
Code cleanup, minor tweaks, new features

### PR DESCRIPTION
**Pull request by DerpgonCz**
Done lots of code cleanup (mostly because of confusing parts, or just to make it look a bit nicer), some minor tweaks and added Hall of Fame feature, fully working only when DB is connected!

### CODE REVIEW

**Comment by TempestCraft** [comment]
I hope this gets committed.

**Comment by Double0negative** [comment]
We don't ever want to save to config.yml. This causes all comments to be deleted which we don't want. If you want to save data, use system.yml

SettingsManager.getInstance().getSystemConfig();

Also, no block updates unless they are on the main thread. Otherwise we will get very odd side effects.

**Comment by DerpgonCz** [comment]
Also a "/sg stats" command, only available when plugin is connected to DB

**Comment by drtshock** [comment]
Put it all into 1 commit? This is... a lot.

**Comment by DerpgonCz** [comment]
I was trying to get the changes together somehow, but felt like it needs some reviewing and getting attention, and you can always check all changes summarized https://github.com/Double0negative/Survival-Games/pull/13/files

**Comment by DerFlash** [comment]
@DragonCzz You've made multiple commits including fixups. Please review the git man page about how to rebase your commits into a smaller amount. Then force push them again.
Also you really should use a branch for creating updates for pull requests, so you may make your own additions later to your master branch without modifying the pull request itself.

**Comment by DerpgonCz** [comment]
Well, I know how to rebase them, but I have some conflicts here, dunno why, will try to do it somehow different.

**Pull request closed without merging**
