### PR TITLE
Code cleanup, added features, fixed bugs

### PR DESCRIPTION
**Pull request by DerpgonCz**
Added:
    Hall of Fame + commands
    /sg stats
    Almost everything can be translated
Edited:
    Auto-Assign now leading to most populated arena
    Some wrong grammar and typos
Fixed:
    No more unknown weapon and unknown killer when player leaves arena when ingame
    Some console spam
Removed:
    Useless usings and whitespaces
Extra:
    Code cleanup
    Every permission is now taken from the class directly

### CODE REVIEW

**Comment by DerFlash** [comment]
Hey again.

At first I need to say: I'm not trying to be rude or picky and for sure the final statement belongs to the admins & owner(s) of the project, but be sure I'm trying to help you here to understand how a PR should be made in my eyes. This just helps the whole project at the end.

You said you know how to rebase with GIT, yet you (again) throw in another fixup instead of rebasing it with the first commit within your master branch + using a force push to update the remote repo.
Just keep in mind that when the author pulls your PR this followup commit will be visible to all users and may just confuse other people.

Also in the last PR you've created a lot of double commits and so on and now fixed it placing all this in just one (or two) commit which is just the opposite of what you did the last time - and also makes not much sense, sry. ;-)
Instead it would be nice to have single commits for every bigger "thing" you've changed. Like one for the clean up, one for another feature and so on. So people could see what exactly you've changed and when. Also when the author decides to only use some parts of it, he could cherry pick some of the commits manually.

One third thing I saw in your commits by just a small first look at it: you've made github updating nealry EVERY file just because you've removed new lines at the end. This makes your commit just a huge "mess" - still not trying to be rude, just to help here.

So - at least in my eyes - you really need to learn some small things and I hope you can do it by just updating your PR here step by step and it may finally help us all to make the plugin even better!

Thanks for your time :-)

**Comment by DerpgonCz** [comment]
Right now, I will just keep it as it is, because I won't spend another 10 hours looking for what I changed where, when and why. Next time, I will make it better, cuz I really messed this one up (dunno why, maybe its cuz my problem with 'think before doing').

I tried to build it and run it on my own server (~50 people) and they didn't notice any bugs (same when I ran it on localhost)

Anyway, thanks for your advice, I will print it and stick it somewhere visible :+1:

**Comment by Double0negative** [comment]
There's way to much stuff in this pr for me to really be able to do anything with it.

**Comment by DerpgonCz** [comment]
I am gonna close this request, I will try third and last time

**Comment by KartikChugh** [comment]
How do you add an AutoAssign sign?
I have seen them on a few servers
Is it /sg add wall autoassign ?

**Pull request closed without merging**
